import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { prismaDB } from '@/db'


export default function Home({ movies }) {

  console.log(movies)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {
          movies.map(movie => (
            <div key={movie.id}>
              <h1>{movie.title}</h1>
              <p>{movie.director}</p>
              <p>{movie.year}</p>              
            </div>
          ))
        }
      </main>
    </>
  )
}

export async function getStaticProps() {  
  const movies = await prismaDB.movies.findMany()
  return {
    props: {
      movies
    }
  }

}