import Head from 'next/head'
import Card from '@/components/Card'
import { prismaDB } from '@/db'
import Router from 'next/router'


export default function Home({ movies }) {

  const router = Router;
  const handledMoreMovies = async () => {
    router.replace(router.asPath);
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <nav className="bg-[#8F37FF] w-screen text-white">
        <h1 className='p-4 text-5xl text-center'>Dev.F IMDB</h1>        
      </nav>
      <section className='productos gap-1'>
          { movies.map((movie) => <Card key={movie.id} movie={movie} />)}
      </section>
      <button 
      onClick={() => handledMoreMovies()}
      className='bg-[#8F37FF] text-white p-4 rounded-lg text-2xl'>Añadir película</button>
    </main>
    </>
  )
}

export async function getStaticProps() {  
  const movies = await prismaDB.movies.findMany({ orderBy: { id: 'desc' } })  
  return {
    props: {
      movies: JSON.parse(JSON.stringify(movies))
    }
  }

}